Add candies to cart
roberto/my-micro-frontends-playground pull request #1
Opened 2018-06-28 17:36 UTC by fmachucas

Adds custom events to intercommunicate apps.
* micro-candy-app throw event with selected candies data.
* stenciljs app, listen to these event and log its content.

2018-06-29 16:51 UTC, roberto commented on micro-candy-app/src/App.js
> +    window.dispatchEvent(new CustomEvent('closeApp'));
:+1:

2018-06-29 16:52 UTC, roberto commented on micro-candy-app/src/App.js
> +
[blank space](https://www.youtube.com/watch?v=e-ORhEE9VVg)

2018-06-29 17:03 UTC, roberto requested changes

2018-06-29 17:03 UTC, roberto commented on micro-candy-app/src/App.js
> +    window.dispatchEvent(new CustomEvent('addToCart', { detail: candies }));
I think we could pass which app is sending the event.
```
{
  details: candies,
  app: 'candy-store' // this should be a constant in the app too.
}
```

2018-07-05 17:23 UTC, roberto approved these changes

2018-07-05 17:23 UTC, roberto commented on micro-candy-app/src/App.js
> +    window.dispatchEvent(new CustomEvent('addToCart', { detail: candies }));
I'm going to add it in another PR. thx!

2018-07-05 17:24 UTC, merged

2018-07-07 10:06 UTC, rogeriochaves commented on stenciljs/my-container/src/components/my-container/my-container.tsx
> +  @Listen('window:addToCart')
💯👌